baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Hugo Blog'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = ""

minify = true

[params]
env = "production"
title = "My Hugo Blog"
description = "A modern blog built with Hugo and PaperMod theme"
keywords = ["blog", "hugo", "papermod"]
author = "Your Name"
images = [""]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = ""
favicon16x16 = ""
favicon32x32 = ""
apple_touch_icon = ""
safari_pinned_tab = ""

[params.label]
text = "Home"
icon = ""
iconHeight = 35

[params.profileMode]
enabled = false
title = ""
subtitle = ""
imageUrl = ""
imageWidth = 120
imageHeight = 120
imageTitle = ""
buttons = []

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog built with Hugo and PaperMod theme"

[[params.socialIcons]]
name = "x"
url = "https://x.com/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/<path_to_repo>/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[menu]
[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "example"
name = "example.org"
url = "https://example.org"
weight = 30

[markup]
[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
style = "github"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
